# Generated by Django 4.2.22 on 2025-07-02 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text="Nombre del curso, ej: 'Cálculo I'", max_length=100, unique=True)),
                ('lista_info', models.TextField(blank=True, help_text='Información adicional o lista de estudiantes (temporal)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text="Nombre o tema de la clase, ej: 'Clase de Límites'", max_length=100)),
                ('horario', models.CharField(help_text="Horario de la clase, ej: 'Lunes 10:00 - 12:00'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='main.curso')),
            ],
        ),
    ]
